name: veyra_client
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter: {sdk: flutter}
  go_router: ^14.2.7
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^3.0.1
dev_dependencies:
  flutter_test: {sdk: flutter}
