package com.veyra.booking;
import com.veyra.security.CurrentUser;import com.veyra.shared.ApiException;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/bookings")public class BookingExtraController{private final JdbcTemplate db;public BookingExtraController(JdbcTemplate d){db=d;}
 @GetMapping("/{id}/pin-status")Map<String,Object>pin(@PathVariable UUID id){Map<String,Object>b=one("select creator_user_id,partner_id,scheduled_at,status,pin_hash from scheduled_bookings where id=?",id);owner(b);boolean visible=OffsetDateTime.now().isAfter(((OffsetDateTime)b.get("scheduled_at")).minusHours(1));return Map.of("available",visible,"note",visible?"PIN is stored securely; retrieve through beneficiary delivery flow":"Available at H-1");}
 @PostMapping("/{id}/cancel")Map<String,Object>cancel(@PathVariable UUID id){Map<String,Object>b=one("select sb.creator_user_id,sb.partner_id,sb.scheduled_at,sb.status,bfs.driver_proposed_amount_minor,bfs.currency from scheduled_bookings sb left join booking_financial_snapshots bfs on bfs.booking_id=sb.id where sb.id=? for update",id);owner(b);if(Set.of("COMPLETED","CLOSED","CANCELLED").contains(b.get("status")))throw new ApiException(HttpStatus.CONFLICT,"CANNOT_CANCEL");long minutes=Duration.between(OffsetDateTime.now(),(OffsetDateTime)b.get("scheduled_at")).toMinutes(),base=b.get("driver_proposed_amount_minor")==null?0:((Number)b.get("driver_proposed_amount_minor")).longValue();int bps=minutes>=360?0:minutes>=120?1000:2500;long fee=BigDecimal.valueOf(base).multiply(BigDecimal.valueOf(bps)).divide(BigDecimal.valueOf(10000),0,RoundingMode.HALF_UP).longValue();db.update("update scheduled_bookings set status='CANCELLED',updated_at=now() where id=?",id);return Map.of("status","CANCELLED","cancellationFeeMinor",fee,"currency",b.get("currency")==null?"EUR":b.get("currency"));}
 public record Rating(@Min(1)@Max(5)int score,String comment,UUID ratedUserId){}
 @PostMapping("/{id}/rating")ResponseEntity<Void>rate(@PathVariable UUID id,@RequestBody Rating r){Map<String,Object>b=one("select creator_user_id,status from scheduled_bookings where id=?",id);if(!CurrentUser.id().equals(b.get("creator_user_id"))||!Set.of("COMPLETED","CLOSED").contains(b.get("status")))throw new ApiException(HttpStatus.FORBIDDEN,"RATING_NOT_ALLOWED");db.update("insert into ride_ratings(booking_id,rater_id,rated_user_id,score,comment) values (?,?,?,?,?)",id,CurrentUser.id(),r.ratedUserId(),r.score(),r.comment());return ResponseEntity.status(201).build();}
 private void owner(Map<String,Object>b){if(CurrentUser.id().equals(b.get("creator_user_id")))return;UUID p=(UUID)b.get("partner_id");if(p!=null&&db.queryForObject("select count(*) from partner_users where partner_id=? and user_id=?",Integer.class,p,CurrentUser.id())>0)return;throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN");}
 private Map<String,Object>one(String q,Object...a){List<Map<String,Object>>x=db.queryForList(q,a);if(x.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND");return x.getFirst();}
}