CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100),email CITEXT UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',failed_login_attempts INT NOT NULL DEFAULT 0,locked_until TIMESTAMPTZ,email_verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE roles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),code VARCHAR(64) UNIQUE NOT NULL,name VARCHAR(120) NOT NULL);
CREATE TABLE user_roles(user_id UUID REFERENCES users(id) ON DELETE CASCADE,role_id UUID REFERENCES roles(id) ON DELETE CASCADE,PRIMARY KEY(user_id,role_id));
CREATE TABLE user_sessions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,refresh_token_hash VARCHAR(64) NOT NULL,device_name VARCHAR(255),expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX ix_sessions_active ON user_sessions(user_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE vehicle_categories(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),code VARCHAR(40) UNIQUE NOT NULL,display_name VARCHAR(100) NOT NULL,capacity SMALLINT NOT NULL CHECK(capacity BETWEEN 1 AND 9),active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE service_zones(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),code VARCHAR(64) UNIQUE NOT NULL,name VARCHAR(120) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE service_zone_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),zone_id UUID NOT NULL REFERENCES service_zones(id),polygon GEOGRAPHY(Polygon,4326) NOT NULL,effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),effective_to TIMESTAMPTZ,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE');
CREATE INDEX ix_zone_polygon ON service_zone_versions USING GIST(polygon);

CREATE TABLE drivers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID UNIQUE NOT NULL REFERENCES users(id),status VARCHAR(24) NOT NULL DEFAULT 'PENDING_KYC',kyc_status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',marketplace_enabled BOOLEAN NOT NULL DEFAULT FALSE,rating NUMERIC(3,2),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE driver_companies(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID UNIQUE NOT NULL REFERENCES drivers(id),siren VARCHAR(16),siret VARCHAR(20),legal_name VARCHAR(180),status VARCHAR(24) NOT NULL DEFAULT 'PENDING');
CREATE TABLE driver_vtc_registrations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID UNIQUE NOT NULL REFERENCES drivers(id),registration_number VARCHAR(80),card_number VARCHAR(80),issued_at DATE,expires_at DATE,status VARCHAR(24) NOT NULL DEFAULT 'PENDING');
CREATE TABLE vehicles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID NOT NULL REFERENCES drivers(id),category_id UUID NOT NULL REFERENCES vehicle_categories(id),brand VARCHAR(80) NOT NULL,model VARCHAR(80) NOT NULL,year SMALLINT NOT NULL,plate_number VARCHAR(32) UNIQUE NOT NULL,color VARCHAR(40),status VARCHAR(20) NOT NULL DEFAULT 'PENDING');
CREATE TABLE driver_documents(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID NOT NULL REFERENCES drivers(id),type VARCHAR(64) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'SUBMITTED',storage_key VARCHAR(512) NOT NULL,original_filename VARCHAR(255),content_type VARCHAR(120),expires_at DATE,rejection_reason_code VARCHAR(64),created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE partner_organizations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name VARCHAR(180) NOT NULL,partner_type VARCHAR(40) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',address_text VARCHAR(500),billing_email VARCHAR(254),credit_status VARCHAR(24) NOT NULL DEFAULT 'PREPAID_ONLY',credit_limit_minor BIGINT NOT NULL DEFAULT 0,currency CHAR(3) DEFAULT 'EUR',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE partner_users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),partner_id UUID NOT NULL REFERENCES partner_organizations(id),user_id UUID NOT NULL REFERENCES users(id),partner_role VARCHAR(32) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',UNIQUE(partner_id,user_id));
CREATE TABLE partner_beneficiaries(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),partner_id UUID NOT NULL REFERENCES partner_organizations(id),full_name VARCHAR(180) NOT NULL,phone VARCHAR(32),email VARCHAR(254),external_reference VARCHAR(100),created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE scheduled_bookings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),creator_type VARCHAR(20) NOT NULL,creator_user_id UUID NOT NULL REFERENCES users(id),partner_id UUID REFERENCES partner_organizations(id),beneficiary_id UUID REFERENCES partner_beneficiaries(id),beneficiary_name_snapshot VARCHAR(180),beneficiary_phone_snapshot VARCHAR(32),pickup GEOGRAPHY(Point,4326) NOT NULL,pickup_address TEXT NOT NULL,dropoff GEOGRAPHY(Point,4326) NOT NULL,dropoff_address TEXT NOT NULL,scheduled_at TIMESTAMPTZ NOT NULL,category_id UUID NOT NULL REFERENCES vehicle_categories(id),payment_method VARCHAR(24) NOT NULL CHECK(payment_method IN('CASH','ONLINE','PARTNER_INVOICE')),payer_type VARCHAR(24) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',selected_offer_id UUID,selected_driver_id UUID REFERENCES drivers(id),offer_window_ends_at TIMESTAMPTZ,pin_hash VARCHAR(255),version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE driver_offers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),booking_id UUID NOT NULL REFERENCES scheduled_bookings(id),driver_id UUID NOT NULL REFERENCES drivers(id),proposed_amount_minor BIGINT NOT NULL CHECK(proposed_amount_minor>0),currency CHAR(3) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',expires_at TIMESTAMPTZ,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE scheduled_bookings ADD CONSTRAINT fk_selected_offer FOREIGN KEY(selected_offer_id) REFERENCES driver_offers(id);
CREATE UNIQUE INDEX ux_offer_active ON driver_offers(booking_id,driver_id) WHERE status='ACTIVE';
CREATE UNIQUE INDEX ux_offer_accepted ON driver_offers(booking_id) WHERE status='ACCEPTED';
CREATE INDEX ix_booking_open ON scheduled_bookings(status,scheduled_at);

CREATE TABLE commission_policy_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),scope_type VARCHAR(24) NOT NULL,partner_id UUID REFERENCES partner_organizations(id),commission_bps INT NOT NULL CHECK(commission_bps BETWEEN 0 AND 10000),version_no INT NOT NULL,status VARCHAR(20) NOT NULL,effective_from TIMESTAMPTZ,effective_to TIMESTAMPTZ);
CREATE TABLE booking_financial_snapshots(booking_id UUID PRIMARY KEY REFERENCES scheduled_bookings(id),offer_id UUID NOT NULL REFERENCES driver_offers(id),commission_policy_id UUID NOT NULL REFERENCES commission_policy_versions(id),commission_rate_bps INT NOT NULL,driver_proposed_amount_minor BIGINT NOT NULL,platform_commission_amount_minor BIGINT NOT NULL,customer_total_amount_minor BIGINT NOT NULL,driver_net_amount_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,payment_method VARCHAR(24) NOT NULL,CHECK(driver_net_amount_minor=driver_proposed_amount_minor),CHECK(customer_total_amount_minor=driver_proposed_amount_minor+platform_commission_amount_minor));
CREATE TABLE driver_platform_debts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID NOT NULL REFERENCES drivers(id),booking_id UUID UNIQUE NOT NULL REFERENCES scheduled_bookings(id),amount_minor BIGINT NOT NULL,paid_amount_minor BIGINT NOT NULL DEFAULT 0,currency CHAR(3) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'DUE');
CREATE TABLE driver_payables(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),driver_id UUID NOT NULL REFERENCES drivers(id),booking_id UUID UNIQUE NOT NULL REFERENCES scheduled_bookings(id),amount_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'PAYABLE');
CREATE TABLE partner_invoice_accounts(partner_id UUID PRIMARY KEY REFERENCES partner_organizations(id),billing_cycle VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',payment_terms_days INT NOT NULL DEFAULT 30,outstanding_minor BIGINT NOT NULL DEFAULT 0,overdue_minor BIGINT NOT NULL DEFAULT 0,status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE partner_invoices(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),partner_id UUID NOT NULL REFERENCES partner_organizations(id),period_start DATE NOT NULL,period_end DATE NOT NULL,total_minor BIGINT NOT NULL,currency CHAR(3) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',due_at DATE);

CREATE TABLE chat_conversations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),booking_id UUID UNIQUE NOT NULL REFERENCES scheduled_bookings(id),status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE chat_messages(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),conversation_id UUID NOT NULL REFERENCES chat_conversations(id),sender_user_id UUID NOT NULL REFERENCES users(id),body VARCHAR(2000) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'SENT',sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),read_at TIMESTAMPTZ);
CREATE TABLE booking_status_history(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),booking_id UUID NOT NULL REFERENCES scheduled_bookings(id),from_status VARCHAR(32),to_status VARCHAR(32) NOT NULL,actor_type VARCHAR(24) NOT NULL,actor_id UUID,reason_code VARCHAR(64),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE current_driver_locations(driver_id UUID PRIMARY KEY REFERENCES drivers(id),booking_id UUID REFERENCES scheduled_bookings(id),lat DOUBLE PRECISION NOT NULL,lng DOUBLE PRECISION NOT NULL,accuracy_m REAL,heading REAL,speed_mps REAL,sequence_no BIGINT NOT NULL,recorded_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE outbox_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),aggregate_type VARCHAR(64) NOT NULL,aggregate_id UUID NOT NULL,event_type VARCHAR(128) NOT NULL,payload JSONB NOT NULL,occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),published_at TIMESTAMPTZ);
CREATE TABLE audit_logs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),actor_id UUID,actor_type VARCHAR(24) NOT NULL,action VARCHAR(128) NOT NULL,entity_type VARCHAR(64),entity_id UUID,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());

INSERT INTO roles(code,name) VALUES ('CLIENT','Client'),('DRIVER','Chauffeur'),('PARTNER_OWNER','Partenaire Owner'),('PARTNER_STAFF','Partenaire Staff'),('PARTNER_FINANCE','Partenaire Finance'),('ADMIN','Admin'),('SUPPORT','Support'),('FINANCE','Finance') ON CONFLICT DO NOTHING;
INSERT INTO vehicle_categories(code,display_name,capacity) VALUES ('STANDARD','Standard',4),('COMFORT','Comfort',4),('VAN','Van',7) ON CONFLICT DO NOTHING;
INSERT INTO commission_policy_versions(scope_type,commission_bps,version_no,status,effective_from) VALUES ('STANDARD',1000,1,'ACTIVE',now());
