package com.veyra.auth;
import com.veyra.shared.ApiException;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/auth") public class AuthController{
 private final UserRepository users;private final PasswordEncoder enc;private final JwtService jwt;private final JdbcTemplate jdbc;private final SecureRandom random=new SecureRandom();
 public AuthController(UserRepository u,PasswordEncoder e,JwtService j,JdbcTemplate d){users=u;enc=e;jwt=j;jdbc=d;}
 public record Register(@Email String email,@Size(min=10,max=128)String password,@NotBlank String firstName,String lastName){}public record Login(@Email String email,@NotBlank String password,String deviceName){}public record Tokens(String accessToken,String refreshToken,UUID userId){}
 @PostMapping("/register") @Transactional ResponseEntity<Tokens> register(@RequestBody Register r){String e=r.email().trim().toLowerCase();if(users.existsByEmailIgnoreCase(e))throw new ApiException(HttpStatus.CONFLICT,"EMAIL_ALREADY_USED");User u=users.save(new User(r.firstName(),r.lastName(),e,enc.encode(r.password())));jdbc.update("insert into user_roles(user_id,role_id) select ?,id from roles where code='CLIENT'",u.id());return ResponseEntity.status(201).body(tokens(u,r.firstName()));}
 @PostMapping("/login") @Transactional Tokens login(@RequestBody Login r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS"));if(u.lockedUntil()!=null&&u.lockedUntil().isAfter(OffsetDateTime.now()))throw new ApiException(HttpStatus.LOCKED,"ACCOUNT_LOCKED");if(!enc.matches(r.password(),u.passwordHash())){u.failed();users.save(u);throw new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS");}if(!"ACTIVE".equals(u.status()))throw new ApiException(HttpStatus.FORBIDDEN,"ACCOUNT_NOT_ACTIVE");u.success();users.save(u);return tokens(u,r.deviceName());}
 private Tokens tokens(User u,String device){List<String>roles=jdbc.queryForList("select r.code from roles r join user_roles ur on ur.role_id=r.id where ur.user_id=?",String.class,u.id());String access=jwt.issue(u.id(),u.email(),roles);byte[]b=new byte[48];random.nextBytes(b);String refresh=Base64.getUrlEncoder().withoutPadding().encodeToString(b);jdbc.update("insert into user_sessions(user_id,refresh_token_hash,device_name,expires_at) values (?,?,?,?)",u.id(),sha(refresh),device,OffsetDateTime.now().plusDays(30));return new Tokens(access,refresh,u.id());}
 private String sha(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}